config/routes.rb
 Sharing::Application.routes.draw do

root 'items#index'

get '/login' => 'sessions#new', as: :sessions
post '/login' => 'sessions#create'
delete '/logout' => 'sessions#destroy', as: :log_out

get '/signup' => 'users#new', as: :signup
get 'users/new' => 'users#new'
post 'users/' => 'users#create'

  get 'items/' => 'items#index'
  post 'items/' => 'items#create'

  get 'items/new' => 'items#new', as: :new_item
  post 'items/' => 'users#create'

  get 'items/:id' => 'items#show', as: :item

  get 'items/:id/edit' => 'items#edit', as: :edit_item
  patch 'items/:id' => 'items#update'

  get 'items/:id/edit' => 'items#edit', as: :return_item
  patch 'items/:id' => 'items#update'

end

app/models/item.rb
class Item
  include Mongoid::Document
  field :name, type: String
  field :status, type: String
  field :condition, type: String

  belongs_to :user
end

app/models/user.rb
# installed gem bcrypt in gemfile
require 'bcrypt'
#  defining a class, User
class User
  include Mongoid::Document

  field :name, type: String
  field :email, type: String
  field :password_digest, type: String
  field :unit, type: Integer

#  I'e defined an assessor method to return the value of an instance variable @password
  attr_reader :password 

  has_many :items

#  This method is asking BCrypt to create a new password hash
# Allows setting of the password
  def password=(new_password)
    self.password_digest = BCrypt::Password.create(new_password)
  end

# test_password is the input from User.
# password_digest is value in db for the key password_digest
# BCrypt reverting back to the password_digest
  def authenticate(test_password)
    if test_password && BCrypt::Password.new(self.password_digest) == test_password
      self
    else
      false
    end
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

 include SessionsHelper

end

app/controllers/items_controller.rb
# I've defined a class, Items.
class ItemsController < ApplicationController

  #  I've defined the index action and I've created an instance variable @items that corresponds to a request for all of them (the collection of each item).
  #  Index handles multiple items, therefore instance variable is plural (@items)
  def index
    @items = Item.all
  end
# Defining the show action and setting an instance variable corresponding to a request for a single item.
  def show
    @item = Item.find(params[:id])
  end

  def new
    @item = Item.new
  end

  def create
    @item = Item.new(params.require(:item).permit(:name, :status, :condition))
    @item.user = current_user  # setting the cu to the owner of item
    if @item.save
      redirect_to items_path
    else
      render 'new'
    end
  end

  def edit
    @item = Item.find(params[:id])
  end

  def update
    @item = Item.find(params[:id])
    if @item.update_attributes(params.require(:item).permit(:name, :status, :condition))
      redirect_to items_path
    else
      render 'edit'
    end
  end

  def destroy
    @item = Item.find(params[:id])
    @item.destroy
    redirect_to items_path
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

    def new
    end

    def create
        begin
            user = User.find_by({email: params[:session][:email]})
        rescue
            flash[:error] = 'Email not found.'          
        end

        if user && user.authenticate(params[:session][:password])
            log_in(user)
            redirect_to root_path
        else
            flash[:error] ||= 'Try again.'
            render 'new'
        end
    end

    def destroy

        log_out
        redirect_to root_path
    end
end

app/controllers/users_controller.rb
 # I'm defining a class, Users
class UsersController < ApplicationController


  def new
    @user = User.new
  end

  def create
    @user = User.new(params.require(:user).permit(:name, :email, :password, :unit))
    if @user.save
      log_in(@user)
      # log the user in
      redirect_to root_path
    else
      render 'new'
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/sessions_helper.rb
  module SessionsHelper

    ################################
    # Ensure current_user returns 
    #    a User object from MongoDB
    ################################

    # LOG IN: set user ID cookie in user's browser
    def log_in(user)
        cookies.permanent[:cookie_id] = user.id

        @current_user = user
    end

    # LOG OUT: remove cookie from user's browser
    def log_out
        cookies.delete(:cookie_id)

    end

    # true if user logged in
    def logged_in?
        cookies[:cookie_id] ? true : false

    end


    ################################
    # Ensure current_user returns 
    #    a User object from MongoDB
    ################################

    # If not already set, retrieve user from MongoDB
    def current_user
        if logged_in?
            @current_user ||= User.find(cookies[:cookie_id])
        else
            nil
        end
    end

    # current_user Setter (similar to attr_writer)
    def current_user=(user)
                @current_user = user
    end
end

app/views/items/_available.html.erb
<body>
  <div class="itemcontainer">

  <div class="available">
    <h2> <%=@item.name %> </h2>

    <p> This <%= @item.name %> is <%= @item.status %> and ready for pick-up from your neighbor at Unit <%= @item.user.unit %>.  Please change status to Unavailable and click "Borrow this item".  Please click here to send an email to your neighbor to schedule a pick up time.
    </p>

      <%= form_for @item do |f| %>
        <%= f.label :name %> <%= f.text_field :name %><br>
        Status: <%= f.select :status, [['Available', 'Available'], ['Unavailable', 'Unavailable']] %><br>
        <%= f.submit "Borrow this item" %>
      <% end %>

          <%= link_to "Back to Share List!", items_path %>
          <%= link_to "Delete your item from the Share List!", @item, method: :delete %>      
  </div>
</div>
</body>

app/views/items/_unavailable.html.erb
<div class="itemcontainer">

 <div class="available">
  <h2> <%=@item.name %> </h2>
   
      <p> This <%= @item.name %> is <%= @item.status %>.  Please check back in a few days for availability.  
      </p>

    <%= link_to "Back to Share List!", items_path %>
    <%= link_to "Return this item", edit_item_path %>
    
  </div>
</div>

app/views/items/edit.html.erb
<div class="itemcontainer">
<h2></h2>

<p> To return this item, please change the status to Available and click "Return this item". </p>



<%= form_for @item do |f| %>
  <%= f.label :name %> <%= f.text_field :name %><br>
  Status: <%= f.select :status, [['Available', 'Available'], ['Unavailable', 'Unavailable']] %><br>



  <%= f.submit "Return this item" %>
  
<% end %>

<%= link_to "Back to the list!", items_path %>

</div>

app/views/items/index.html.erb
<!-- Name of file important b/c it matches route and controller action -->
<div class="container white">
  <h1> Welcome to the SF Cottages Community Sharing </h1>

    <h2>Here is a list of the Share Items:</h2>

      <table class="table">
        <thead>
          <th> Share Item</th>
          <th> Status </th>
          <th> Item Details</th>
        </thead>

        <!-- Index views generally loop through all instances of a given model item -->
        <% @items.each do |i| %>
          <tr>
            <!-- the loop populates the list item tags with each item's name and availability -->
            <td> <%= i.name %> </td>  
            <td> <%= i.status %> </td>
            <td> <%= link_to "Show details!", item_path(i), class: "btn btn-primary" %>  </td>
          </tr>
        <% end %>
      </table>

    <%= link_to "Add your item to the Share List", new_item_path, class: "btn btn-primary" %>
    



  <% if !logged_in? %>
    <%= link_to "Sign Up & Join", users_new_path, class: "btn btn-primary" %>
    <%= link_to "Sign In", sessions_path, class: "btn btn-primary" %>
  <% end %>
      
</div>

app/views/items/new.html.erb
<div class="itemcontainer">

<h2> Add an item to share with your neighbors! </h2>

<%= form_for @item do |f| %>
  <%= f.label :item_name %>
  <%= f.text_field :name %>

  <%= f.label :status %>
  <%= f.text_field :status %>

  <%= f.label :condition %>
  <%= f.text_field :condition %>

  <%= f.submit "Add your item to the Share List" %> <%= link_to "Back to the Community Share List", items_path %>

  <% end %>
</div>

app/views/items/show.html.erb
<% if @item.status == "Available" %>
  <%= render "available" %>
  <% else %>
  <%= render "unavailable" %>
  <% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Sharing</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

  <header>
    San Francisco Cottages Homeowners Association
  </header>


  <div class="maintext"
    <% if logged_in? %>
      <p> You're logged in! </p>
      <%= link_to  "Log Out", log_out_path, class: "btn btn-primary", method: :delete %>
     
    <% end %>
  </div>

  <%= yield %>

</body>
</html>

app/views/users/new.html.erb
<div class="itemcontainer">
<h2>Sign Up to Join the Community Share!</h2>

<%= form_for @user do |f| %>
  <%= f.label :name %> 
  <%= f.text_field :name %>

  <%= f.label :unit %> 
  <%= f.text_field :unit %>

  <%= f.label :email %> 
  <%= f.text_field :email %>

  <%= f.label :password %> 
  <%= f.password_field :password %>

  <%= f.submit "Sign Me Up!" %> 


<% end %>

  <%= link_to "Back to the Share List", items_path %>

</div>